# Generated by Django 6.0 on 2025-12-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='default_password', max_length=255),
            preserve_default=False,
        ),
    ]
