# Generated by Django 5.2.7 on 2025-12-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_service_options_service_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='staff',
        ),
        migrations.AddField(
            model_name='service',
            name='staff',
            field=models.ManyToManyField(related_name='services', to='appointments.customuser'),
        ),
    ]
