# Generated by Django 5.2.7 on 2025-12-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_remove_service_staff_service_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('serving', 'Serving'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('confirmation', 'Confirmation'), ('approval', 'Approval'), ('rejection', 'Rejection'), ('reminder', 'Reminder'), ('cancellation', 'Cancellation'), ('edited', 'Edited')], default='confirmation', max_length=20),
        ),
    ]
