# Generated by Django 5.2.7 on 2026-01-01 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_appointments', to='appointments.customuser'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('confirmation', 'Confirmation'), ('approval', 'Approval'), ('rejection', 'Rejection'), ('reminder', 'Reminder'), ('cancellation', 'Cancellation'), ('edited', 'Edited'), ('booking', 'Booking')], default='confirmation', max_length=20),
        ),
    ]
