# Generated by Django 5.2.7 on 2026-01-01 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='appointments.appointment'),
        ),
    ]
